const CONTENT = [
  {
    type: "tip",
    text: "Use the rule of thirds to create balanced and engaging shots.",
  },
  {
    type: "tip",
    text: "Good audio quality is often more important than video quality.",
  },
  { type: "tip", text: "Use a tripod or stabilizer to avoid shaky footage." },
  {
    type: "tip",
    text: "Frame your subject with proper headroom and lead room.",
  },
  { type: "tip", text: "Shoot in natural light whenever possible." },
  { type: "tip", text: "Record room tone to make audio edits seamless." },
  {
    type: "tip",
    text: "Use B-roll to smooth transitions and add visual interest.",
  },
  { type: "tip", text: "Keep your shots steady and intentional." },
  { type: "tip", text: "Avoid overusing zoom—move the camera instead." },
  { type: "tip", text: "Always monitor your audio with headphones." },
  { type: "tip", text: "Use manual focus for more control over your shot." },
  { type: "tip", text: "Check your white balance before recording." },
  { type: "tip", text: "Keep backgrounds simple to avoid distractions." },
  { type: "tip", text: "Use leading lines to guide the viewer’s eye." },
  {
    type: "tip",
    text: "Shoot extra footage to give yourself options in editing.",
  },
  { type: "tip", text: "Use a clap or slate to sync audio and video." },
  { type: "tip", text: "Plan your shots ahead of time with a storyboard." },
  { type: "tip", text: "Shoot interviews at eye level for a natural look." },
  { type: "tip", text: "Use soft lighting to reduce harsh shadows." },
  { type: "tip", text: "Always clean your lens before filming." },
  { type: "tip", text: "Use consistent lighting for continuity." },
  { type: "tip", text: "Avoid backlighting your subject unless intentional." },
  { type: "tip", text: "Capture establishing shots to set the scene." },
  { type: "tip", text: "Use cutaways to hide edits." },
  { type: "tip", text: "Keep your camera movements slow and smooth." },
  { type: "tip", text: "Record more takes than you think you need." },
  { type: "tip", text: "Use external microphones for clearer sound." },
  { type: "tip", text: "Keep your horizon level in wide shots." },
  { type: "tip", text: "Use color to set the mood of your scene." },
  { type: "tip", text: "Test your equipment before every shoot." },

  { type: "fact", text: "Most films are shot at 24 frames per second." },
  { type: "fact", text: "4K video has four times the resolution of 1080p." },
  {
    type: "fact",
    text: "YouTube is the second most visited website in the world.",
  },
  {
    type: "fact",
    text: "Aspect ratio determines the shape of your video frame.",
  },
  {
    type: "fact",
    text: "Sound design can dramatically change a scene’s impact.",
  },
  { type: "fact", text: "Green screens are used for chroma key compositing." },
  { type: "fact", text: "HDR video improves contrast and color range." },
  {
    type: "fact",
    text: "Editing is often called the invisible art of filmmaking.",
  },
  { type: "fact", text: "Streaming services now surpass cable TV viewership." },
  { type: "fact", text: "A storyboard helps visualize scenes before filming." },
  { type: "fact", text: "Wide shots establish location and context." },
  { type: "fact", text: "Close-ups emphasize emotion and detail." },
  { type: "fact", text: "Jump cuts are used to show time passing quickly." },
  { type: "fact", text: "Match cuts create visual continuity between scenes." },
  { type: "fact", text: "Lighting direction affects mood and depth." },
  { type: "fact", text: "Most cameras use sensors instead of film today." },
  { type: "fact", text: "B-roll is supplemental footage used in editing." },
  { type: "fact", text: "A dissolve transition suggests passage of time." },
  { type: "fact", text: "Color grading enhances the look of footage." },
  { type: "fact", text: "The 180-degree rule maintains spatial consistency." },
  { type: "fact", text: "Foley artists create everyday sound effects." },
  { type: "fact", text: "Depth of field controls background blur." },
  { type: "fact", text: "Frame rate affects motion appearance." },
  {
    type: "fact",
    text: "Compression reduces file size but can affect quality.",
  },
  {
    type: "fact",
    text: "Live broadcasting requires minimal delay processing.",
  },
  { type: "fact", text: "Public access TV allows community-created content." },
  { type: "fact", text: "Nonlinear editing allows instant access to clips." },
  { type: "fact", text: "Color temperature is measured in Kelvin." },
  { type: "fact", text: "Audio levels are measured in decibels." },
  { type: "fact", text: "Metadata helps organize video files." },

  {
    type: "history",
    text: "The first public film screening took place in 1895.",
  },
  { type: "history", text: "The Lumière brothers pioneered early filmmaking." },
  { type: "history", text: "The first Academy Awards were held in 1929." },
  { type: "history", text: "Color film became popular in the 1930s." },
  { type: "history", text: "The Steadicam was invented in 1975." },
  { type: "history", text: "Public access television expanded in the 1970s." },
  { type: "history", text: "The VHS format launched in 1976." },
  {
    type: "history",
    text: "Digital editing replaced film editing in the 1990s.",
  },
  { type: "history", text: "HD broadcasting became standard in the 2000s." },
  { type: "history", text: "Streaming services rose in the early 2000s." },
  {
    type: "history",
    text: "The first televised presidential debate was in 1960.",
  },
  { type: "history", text: "The dolly zoom was popularized in Vertigo." },
  {
    type: "history",
    text: "The first animated feature film was released in 1937.",
  },
  { type: "history", text: "Cable television expanded rapidly in the 1980s." },
  {
    type: "history",
    text: "Nonlinear editing systems revolutionized filmmaking.",
  },
  { type: "history", text: "Early films were silent and black and white." },
  { type: "history", text: "Sound films emerged in the late 1920s." },
  { type: "history", text: "The first video cameras used magnetic tape." },
  { type: "history", text: "Portable cameras changed documentary filmmaking." },
  {
    type: "history",
    text: "Satellite broadcasting expanded global media reach.",
  },
  { type: "history", text: "Digital cameras became dominant in the 2010s." },
  {
    type: "history",
    text: "Streaming platforms transformed content distribution.",
  },
  { type: "history", text: "Public media supports local storytelling." },
  { type: "history", text: "Film festivals showcase independent filmmakers." },
  { type: "history", text: "Community media centers empower local voices." },
  { type: "history", text: "Editing once required physically cutting film." },
  { type: "history", text: "Early TV broadcasts were live only." },
  { type: "history", text: "Color television became widespread in the 1960s." },
  { type: "history", text: "Home video made films widely accessible." },
  { type: "history", text: "Digital streaming reshaped media consumption." },

  { type: "tip", text: "Use three-point lighting for balanced illumination." },
  { type: "tip", text: "Keep interviews in quiet environments." },
  { type: "tip", text: "Use consistent framing across shots." },
  {
    type: "tip",
    text: "Shoot at higher resolution for flexibility in editing.",
  },
  { type: "tip", text: "Use markers to hit focus points." },
  { type: "tip", text: "Avoid clipping highlights in bright scenes." },
  { type: "tip", text: "Use slow motion sparingly for emphasis." },
  { type: "tip", text: "Organize your footage before editing." },
  { type: "tip", text: "Back up your media files regularly." },
  { type: "tip", text: "Use transitions intentionally, not excessively." },

  { type: "fact", text: "Frame composition affects storytelling clarity." },
  { type: "fact", text: "Audio delay can disrupt viewer experience." },
  { type: "fact", text: "High bitrate improves video quality." },
  { type: "fact", text: "Lighting can define character mood." },
  { type: "fact", text: "Visual effects enhance storytelling." },

  {
    type: "history",
    text: "Independent films gained popularity in the 1990s.",
  },
  { type: "history", text: "Digital cinema replaced film projection." },
  {
    type: "history",
    text: "Online video platforms democratized content creation.",
  },
  {
    type: "history",
    text: "Community media continues to evolve with technology.",
  },
  {
    type: "history",
    text: "Modern editing software allows real-time playback.",
  },
];
